[colors.bright]
black = "0x686868"
blue = "0x59C2FF"
cyan = "0x95E6CB"
green = "0xC2D94C"
magenta = "0xFFEE99"
red = "0xF07178"
white = "0xFFFFFF"
yellow = "0xFFB454"

[colors.cursor]
cursor = "0xffff99"
text = "0x191622"

[colors.dim]
black = "0x000000"
blue = "0x1818b2"
cyan = "0x18b2b2"
green = "0x18b218"
magenta = "0xb218b2"
red = "0xb21818"
white = "0xb2b2b2"
yellow = "0xb26818"

[colors.normal]
black = "0x01060E"
blue = "0x53BDFA"
cyan = "0x90E1C6"
green = "0x91B362"
magenta = "0xFAE994"
red = "0xEA6C73"
white = "0xC7C7C7"
yellow = "0xF9AF4F"

[colors.primary]
background = "0x0A0E14"
foreground = "0xFFFFFF"

[colors.search.focused_match]
background = "CellForeground"
foreground = "CellBackground"

[colors.search.matches]
background = "0xb26818"
foreground = "0xb2b2b2"

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
#family = "JetBrains Mono"
family = "terminal-font"
style = "Bold"

[font.bold_italic]
#family = "JetBrains Mono"
family = "terminal-font"
style = "Bold Italic"

[font.italic]
#family = "JetBrains Mono"
family = "terminal-font"
style = "Italic"

[font.normal]
#family = "JetBrains Mono"
family = "terminal-font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 5
y = 5
