#!/bin/bash

i3 restart
setxkbmap us
# set default sink: Cannon Point-LP High Definition Audio Controller HDMI / DisplayPort 2 Output
pactl set-default-sink alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_4__sink
notify-send -i display "Display profile" "$AUTORANDR_CURRENT_PROFILE"
